/**
 * This script is only needed to make vite preview work like a real bundled webcomponent preview.
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";

mkdirSync("public", { recursive: true });

const html = readFileSync("index.html", "utf-8");
const comment = `<!-- This file was generated by scripts/copy-index.ts from the root index.html. Do not edit it directly. -->\n`;
const replaced =
  comment + html.replace(`/src/main.ts`, `/modal-example.esm.js`);

writeFileSync("public/index.html", replaced);
